name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Get EC2 Instance IP
        id: get_ip
        run: |
          echo "instance_ip=$(terraform output -json instance_ip | jq -r .)" >> $GITHUB_ENV

      - name: Use EC2 Instance IP
        run: echo "The public IP of the EC2 instance is $instance_ip"
